# Generated by Django 5.2.17 on 2026-10-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0004_global_admin_sql_policy'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerarea',
            name='area',
            field=models.ForeignKey(db_column='area_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.area'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='area',
            field=models.ForeignKey(blank=True, db_column='area_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.area'),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
