# Generated by Django 5.2.17 on 2026-10-07 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0005_alter_workerarea_area_delete_area'),
        ('workers', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerarea',
            name='worker',
            field=models.ForeignKey(db_column='trabajador_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='workers.worker'),
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
